import { TemplateConfig } from '../types.js';

const templates: Record<string, TemplateConfig> = {
  'note-analysis': {
    name: 'my-note-analysis-extension',
    description: 'Provides note analysis',
    version: '0.0.1',
    tools: [
      {
        name: 'note-analyzer',
        description: 'Provides analysis of a note',
        endpoint: 'https://publisher.example.com/note-analysis',
        trigger: 'AutoRun',
        inputs: [
          {
            name: 'note',
            description: 'Clinical Note generated by dragon copilot',
            'content-type': 'application/vnd.ms-dragon.dsp.note+json'
          }
        ],
        outputs: [
          {
            name: 'coded-note-analysis-results',
            description: 'Note analysis results in coded format',
            'content-type': 'application/vnd.ms-dragon.dsp+json'
          },
          {
            name: 'note-analysis-results-adaptive-card',
            description: 'Note analysis results in Adaptive Card format',
            'content-type': 'application/vnd.ms-dragon.dsp+json'
          }
        ]
      }
    ]
  },

  'speech-analysis': {
    name: 'my-speech-extension',
    description: 'Provides speech analysis',
    version: '0.0.1',
    tools: [
      {
        name: 'speech-analysis',
        description: 'Provides analysis of iterative speech',
        endpoint: 'https://publisher.example.com/speech-analysis',
        trigger: 'AutoRun',
        inputs: [
          {
            name: 'iterative-transcript',
            description: 'Iterative transcript',
            'content-type': 'application/vnd.ms-dragon.dsp.iterative-transcript+json'
          },
          {
            name: 'iterative-audio',
            description: 'Iterative audio',
            'content-type': 'application/vnd.ms-dragon.dsp.iterative-audio+json'
          }
        ],
        outputs: [
          {
            name: 'speech-analysis-results-adaptive-card',
            description: 'Speech analysis results in Adaptive Card format',
            'content-type': 'application/vnd.ms-dragon.dsp+json'
          },
          {
            name: 'coded-speech-analysis-results',
            description: 'Speech analysis results in coded format',
            'content-type': 'application/vnd.ms-dragon.dsp+json'
          }
        ]
      }
    ]
  }
};

export function getTemplate(templateName: string): TemplateConfig {
  const template = templates[templateName];
  if (!template) {
    throw new Error(`Template '${templateName}' not found. Available templates: ${Object.keys(templates).join(', ')}`);
  }
  return template;
}

export function listTemplates(): string[] {
  return Object.keys(templates);
}
