name: Security

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    # Run weekly on Sundays at 2 AM UTC
    - cron: '0 2 * * 0'

jobs:
  security-scan:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.0.x'

    - name: Restore dependencies
      run: |
        cd src/Dragon.Copilot.Models && dotnet restore
        cd ../../samples/DragonCopilot/Workflow && dotnet restore

    - name: Run security audit
      run: |
        cd src/Dragon.Copilot.Models && dotnet list package --vulnerable --include-transitive
        cd ../../samples/DragonCopilot/Workflow && dotnet list package --vulnerable --include-transitive

    - name: Check for outdated packages
      run: |
        cd src/Dragon.Copilot.Models && dotnet list package --outdated
        cd ../../samples/DragonCopilot/Workflow && dotnet list package --outdated

  codeql-analysis:
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write

    steps:
    - uses: actions/checkout@v4

    - name: Initialize CodeQL
      uses: github/codeql-action/init@v3
      with:
        languages: csharp, javascript

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.0.x'

    - name: Restore and build
      run: |
        cd src/Dragon.Copilot.Models
        dotnet restore
        dotnet build --no-restore --configuration Release
        cd ../../samples/DragonCopilot/Workflow
        dotnet restore
        dotnet build --no-restore --configuration Release

    - name: Perform CodeQL Analysis
      uses: github/codeql-action/analyze@v3
